version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=PRODUCTION
      - APP_SECRET_KEY=
      - APP_ACCESS_TOKEN_COOKIE_NAME=
      - APP_ACCESS_TOKEN_EXPIRE=
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_REGION=
      - OTLP_GRPC_ENDPOINT=
      - CORS_ALLOWED_ORIGINS=
      - CORS_ALLOW_METHODS=
      - CORS_ALLOW_HEADERS=
      - CORS_ALLOW_CREDENTIALS=
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8080
      - UVICORN_RELOAD=false
      - UVICORN_WORKERS=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:

environment:
  - POSTGRES_USER=
  - POSTGRES_PASSWORD=
  - POSTGRES_DB=

volumes:
  pg_data:
    driver: "local"
