"""Store price as decimal

Revision ID: 1bca19294bf2
Revises: 818b9a1a01dc
Create Date: 2023-05-21 14:10:13.151875

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1bca19294bf2"
down_revision = "818b9a1a01dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment",
        "price",
        existing_type=sa.Float(),
        type_=sa.Numeric(precision=12, scale=0),
    )
    op.alter_column(
        "timeframe",
        "price",
        existing_type=sa.Float(),
        type_=sa.Numeric(precision=12, scale=0),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "timeframe",
        "price",
        existing_type=sa.Numeric(precision=12, scale=0),
        type_=sa.Float(),
    )
    op.alter_column(
        "payment",
        "price",
        existing_type=sa.Numeric(precision=12, scale=0),
        type_=sa.Float(),
    )
    # ### end Alembic commands ###
