"""Add price to reservation

Revision ID: 4e6465dec8ea
Revises: c379c95dbda1
Create Date: 2023-06-20 22:54:01.167376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e6465dec8ea"
down_revision = "c379c95dbda1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column("price", sa.Numeric(precision=12, scale=0), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservation", "price")
    # ### end Alembic commands ###
