"""Add image url, remove FacilityImage relationship

Revision ID: 721589165bbd
Revises: f25a8a9225d2
Create Date: 2023-06-20 21:50:21.154970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "721589165bbd"
down_revision = "f25a8a9225d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("facility", sa.Column("image_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("facility", "image_url")
    # ### end Alembic commands ###
