"""Add lat,lon

Revision ID: 818b9a1a01dc
Revises: affbfd1377cb
Create Date: 2023-05-21 13:28:30.747115

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "818b9a1a01dc"
down_revision = "affbfd1377cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facility",
        sa.Column("lat", sa.Numeric(precision=10, scale=8), nullable=False),
    )
    op.add_column(
        "facility",
        sa.Column("lon", sa.Numeric(precision=11, scale=8), nullable=False),
    )
    op.drop_column("facility", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservation", "timeframe_id", existing_type=sa.UUID(), nullable=True
    )
    op.add_column(
        "facility",
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("facility", "lon")
    op.drop_column("facility", "lat")
    # ### end Alembic commands ###
