"""Remove fk

Revision ID: f559f0116b31
Revises: 18e253704999
Create Date: 2023-11-07 08:49:03.632572

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f559f0116b31"
down_revision = "18e253704999"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservation", "facility_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        "reservation_timeframe_id_fkey", "reservation", type_="foreignkey"
    )
    op.drop_column("reservation", "timeframe_id")
    op.drop_constraint("uq_timeframe_id", "timeframe", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_timeframe_id", "timeframe", ["id"])
    op.add_column(
        "reservation",
        sa.Column("timeframe_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "reservation_timeframe_id_fkey",
        "reservation",
        "timeframe",
        ["timeframe_id"],
        ["id"],
    )
    op.alter_column(
        "reservation", "facility_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
