"""Add facility image

Revision ID: 18e253704999
Revises: 97546f26a816
Create Date: 2023-10-15 21:12:42.625686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18e253704999"
down_revision = "97546f26a816"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("facility", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "facility",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
